/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProduceRouteImport } from './routes/produce'
import { Route as FisheriesRouteImport } from './routes/fisheries'
import { Route as IndexRouteImport } from './routes/index'

const ProduceRoute = ProduceRouteImport.update({
  id: '/produce',
  path: '/produce',
  getParentRoute: () => rootRouteImport,
} as any)
const FisheriesRoute = FisheriesRouteImport.update({
  id: '/fisheries',
  path: '/fisheries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fisheries': typeof FisheriesRoute
  '/produce': typeof ProduceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fisheries': typeof FisheriesRoute
  '/produce': typeof ProduceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fisheries': typeof FisheriesRoute
  '/produce': typeof ProduceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fisheries' | '/produce'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fisheries' | '/produce'
  id: '__root__' | '/' | '/fisheries' | '/produce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FisheriesRoute: typeof FisheriesRoute
  ProduceRoute: typeof ProduceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produce': {
      id: '/produce'
      path: '/produce'
      fullPath: '/produce'
      preLoaderRoute: typeof ProduceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fisheries': {
      id: '/fisheries'
      path: '/fisheries'
      fullPath: '/fisheries'
      preLoaderRoute: typeof FisheriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FisheriesRoute: FisheriesRoute,
  ProduceRoute: ProduceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
